trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: CmdLine@2
  inputs:
    script: |
      npm install -g swaggerhub-cli
      swaggerhub api:export Alex/<1 --username alexliga1998 --token 9a4df898-c8ef-4f5d-8154-b138d3d5b12b api-definition.yaml
  displayName: 'Export API definition from SwaggerHub'
